MODEL:
  META_ARCHITECTURE: Baseline

  BACKBONE:
    NAME: build_resnet_backbone
    NORM: BN
    DEPTH: 50x
    LAST_STRIDE: 1
    FEAT_DIM: 2048
    WITH_IBN: True
    PRETRAIN: True
    PRETRAIN_PATH: /home/helingxiao3/.cache/torch/checkpoints/resnet50_ibn_a-d9d0bb7b.pth

  HEADS:
    NAME: EmbeddingHead
    NORM: BN
    WITH_BNNECK: True
    POOL_LAYER: avgpool
    NECK_FEAT: before
    CLS_LAYER: linear

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)

    CE:
      EPSILON: 0.1
      SCALE: 1.

    TRI:
      MARGIN: 0.3
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 1.

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  REA:
    ENABLED: True
    PROB: 0.5
  DO_PAD: True

DATALOADER:
  PK_SAMPLER: True
  NAIVE_WAY: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  FP16_ENABLED: False
  OPT: SGD
  SCHED: CosineAnnealingLR
  MAX_EPOCH: 30
  BASE_LR: 0.04
  BIAS_LR_FACTOR: 1.
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 256
  
  ETA_MIN_LR: 0.00004
  
  FREEZE_ITERS: 2000
  FREEZE_FC_ITERS: 0
  
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 4000
  
  CHECKPOINT_PERIOD: 3
  
TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 512

CUDNN_BENCHMARK: True
